### ISSUE TITLE
Package conflicts 

### ISSUE THREAD

**Issue by seisdr** [termux/termux-styling#197]
* Termux application version: 0.118.0
* Android OS version: 13
* Device model:
F-droid version

**Comment by Grimler91** [comment]
?

**Comment by seisdr** [comment]
I can't install termux styling because it's conflict with another package

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-app#installation

**Comment by lxender** [comment]
This issue is not resolved.
I have the same issue, I downloaded the entire Termux stack from Github, but cannot install this package due to "conflicts with another package". The Github tag includes the f-droid version in the release [0.30](https://github.com/termux/termux-styling/releases/tag/v0.30)

**Comment by lxender** [comment]
@seisdr You most likely mixed the installations. You cannot install Termux from two different sources. This is what @agnostic-apollo attempted to communicate. You must either install every Termux app from F-Droid or the Github Releases that the specific repo provides.

**Comment by agnostic-apollo** [comment]
That shouldn't be done, it will confuse users. Something like https://github.com/termux/termux-float/commit/529268a1 should be done instead.
