### ISSUE TITLE
#Help I'm not getting colors

### ISSUE THREAD

**Issue by SamSanuch** [termux/termux-styling#27]
I have purchased termux styling from Google play store but i think it's a waste of money for me as i can't get colours working ,I'm on stock miui ROM it supports the colours but it overlay it i need help

**Comment by Neo-Oli** [comment]
Can you explain how it is not working?
Do you get any error messages when you're trying to select a color?

**Comment by SamSanuch** [comment]
@Neo-Oli
See this video
https://drive.google.com/file/d/1Yxm75M5qB1glEZNktL9g_QO-EB8qjgf6/view?usp=drivesdk

**Comment by Neo-Oli** [comment]
@SamSanuch Video is Private. Please make it public.

**Comment by SamSanuch** [comment]
@Neo-Oli 
Done!

**Comment by Neo-Oli** [comment]
You have enabled the Android Accessibility feature "High contrast text". You need to disable that in `Settings -> Accessibility -> High contrast text` in order for colors to work. Otherwise Android will (correctly) remove the colors from text to make it more easily readable for the visually impaired.

**Comment by SamSanuch** [comment]
@Neo-Oli thanks solved !
I have send you an request at Facebook please except

**Comment by Neo-Oli** [comment]
> I have send you an request at Facebook please except

No

**Comment by STAR-Sec** [comment]
How do I reset to default?

**Comment by xeffyr** [comment]
@STAR-Sec Choose color scheme "default".
