### ISSUE TITLE
Add option for cursor face custimization

### ISSUE THREAD

**Issue by cdfa** [termux/termux-styling#38]
Sometimes it's very hard to read the character which the cursor is on because of low contrast. It would be nice if this add-on had a way of changing it's colour.

**Comment by xeffyr** [comment]
Actually, this is because of how themes were created and this affects not only cursor but text selection too.

Many themes have cursor color same as foreground. For example, 'Base16 Eighties' theme:
```
# https://github.com/chriskempson/base16-xresources/blob/master/base16-eighties.dark.256.xresources
# Base16 Eighties
# Scheme: Chris Kempson (http://chriskempson.com)
foreground=#d3d0c8
background=#2d2d2d
cursor=#d3d0c8

color0=#2d2d2d
color1=#f2777a
color2=#99cc99
color3=#ffcc66
color4=#6699cc
color5=#cc99cc
color6=#66cccc
color7=#d3d0c8
color8=#747369
color9=#f2777a
color10=#99cc99
color11=#ffcc66
color12=#6699cc
color13=#cc99cc
color14=#66cccc
color15=#f2f0ec

color16=#f99157
color17=#d27b53
color18=#393939
color19=#515151
color20=#a09f93
color21=#e8e6df
```

On original theme selected text is invisible:
![invisible text](https://user-images.githubusercontent.com/25881154/43658766-78d78a32-9762-11e8-8b43-a9ff3dab34b7.jpg)

But if line `cursor=#d3d0c8` will be replaced with `cursor=#a3a098`, then issue will be solved:
![visible text](https://user-images.githubusercontent.com/25881154/43658770-7b8d2d22-9762-11e8-9944-d4b9c6a47657.jpg)

**Comment by cdfa** [comment]
Okay, but if I want to keep the default theme, the file only says "# using default theme", so I can't change the colour. Could you point me to where the default theme is defined so I can paste it in there?

Another small question: is there a file I can open that contains text in all the colours defined in the theme so I can "test" what a theme looks like?

**Comment by cdfa** [comment]
> Okay, but if I want to keep the default theme, the file only says "# using default theme", so I can't change the colour.

Never mind, it works by just appending it to the file.
