### ISSUE TITLE
Open source paid app?

### ISSUE THREAD

**Issue by scoopgracie** [termux/termux-styling#97]
Is this the same as the $1.99 Termux:Styling app on the play store?

**Comment by Grimler91** [comment]
Yes (also available on F-droid)

**Comment by SDRausty** [comment]
It's great it's open source, isn't it @scoopgracie?

**Comment by scoopgracie** [comment]
Yeah it is. Having the same app paid on Google play and free on f droid
just confused me.

**Comment by SDRausty** [comment]
> just confused

https://wiki.termux.com/wiki/Installation

**Comment by scoopgracie** [comment]
No, not confused as in how do I install this, confused as in what's the
point of a paid app if you offer it for free somewhere else

**Comment by SDRausty** [comment]
I mentioned this link because it explains a little bit more about F Droid and Google Play.  

> what's the point of a paid app if you offer it for free 

That's is a good question.  Hopefully, someone will come along and enlighten us as to the answer.  In the meantime, I can propose a couple of reasons why someone might want to have a paid app, and also have it open source:
1 Money
2 Cash
3 Sharing
4 Publishing
Can you add any to this list @scoopgracie?  I'd like to see more reasons why.

**Comment by xeffyr** [comment]
There is one simple reason @SDRausty - donation.  If you don't want to donate, then use entirely free variants - F-Droid or custom build from source.

GPL license, under which Termux and add-ons were released, does not prohibit selling software as soon as its source code is also provided.

**Comment by xeffyr** [comment]
Issue is locked as started to go beyond the topic.
